"""Single source of truth for every short, hand-authored phrase the
assistant might speak that isn't generated by the SLM.

All of the audio caches in `core/assistant.py` are built from these lists
in `_warm_and_announce`; editing a phrase here is the only step needed to
change what the user hears.
"""

# Fallback text returned when the agent emits an empty `reply` or empty
# `actions` — the caller speaks it live via the normal TTS path, so this
# is a plain string list (no pre-rendering needed).
STALL_PHRASES = [
    "Okay, let me think.",
    "Hold on a second.",
    "Got it, give me a moment.",
    "Let me see.",
]

# === Startup-cached phrases ==================================================
#
# These are the only phrases synthesized during startup. Edit this section to
# change both what is immediately available and how much startup TTS work is
# done. The generic set is deliberately shared by acknowledgements, busy
# replies, and all tool/thinking stall contexts.

STARTUP_SHARED_PHRASES = [
    "Okay.",
    "One moment.",
    "Working on that.",
]

# Cache attributes that reuse STARTUP_SHARED_PHRASES rather than each rendering
# their own phrase pool.
STARTUP_SHARED_CACHE_ATTRS = (
    "ack_cache",
    "busy_cache",
    "web_search_stall_cache",
    "note_write_stall_cache",
    "pre_thinking_stall_cache",
    "thinking_stall_cache",
    "replan_stall_cache",
)

# Single lead-in phrase played just before a note write/append/remember so
# the user hears activity during the SLM → tool → reply gap. Pre-rendered.
NOTE_WRITE_STALL_PHRASES = [
    "Writing that down.",
    "Saving that now.",
    "Got it, noting that.",
    "On it, jotting that down.",
]

# Single lead-in phrase played just before kicking off a web search +
# summary, so the user knows what's happening during the ~1s gap before
# the spoken answer. Context-specific so they hear "searching the web"
# rather than a generic "let me see". Pre-rendered at warmup.
WEB_SEARCH_STALL_PHRASES = [
    "Searching the web.",
    "Looking that up online.",
    "Let me check online.",
    "Pulling that from the web.",
]

# Single lead-in phrase played just before a thinking-mode replan begins
# — the `ThinkingWatchdog` then takes over with periodic stalls during
# the long /think run.
PRE_THINKING_STALL_PHRASES = [
    "Let me think on that.",
    "I'll think this through.",
    "Thinking it over.",
    "Working through that.",
]

# Short acknowledgement spoken in parallel with the first SLM call of an
# agent-path turn so the user knows their wakeword + utterance were heard.
# Skipped on regex fast-path turns (the tool reply itself is fast enough).
# Pre-rendered at warmup.
ACK_PHRASES = [
    "Got it.",
    "Okay.",
    "On it.",
    "Sure thing.",
    "Right.",
]

# Played the moment a "redirect" barge-in (bare wakeword/name, no stop word)
# cancels an in-flight turn and opens the follow-up window. Without this the
# cancellation is silent — a false trigger (cough, TV, ASR hallucination)
# stops whatever the assistant was doing with no audible sign anything
# happened, and the user has no idea their original request was dropped.
# A pure "stop" still stands down silently by design (see _is_pure_stop);
# this only covers the redirect path, where the assistant is now listening.
BARGE_ACK_PHRASES = [
    "Yes.",
]

# Played on a satellite whose turn attempt lost the TurnArbiter (another
# satellite, or a dashboard text turn, already owns it). Short and
# side-stepping rather than apologetic — this is a normal, frequent
# occurrence in a multi-satellite home, not an error. Pre-rendered to
# `busy_cache` in `_warm_and_announce`, played via `_play_busy_phrase`
# (voice) or spoken directly as text (dashboard chat, which has no TTS).
BUSY_PHRASES = [
    "Just a second, I'm already helping out elsewhere.",
    "Give me a moment, I'm mid-conversation.",
    "Hang on, I'm talking to another room.",
    "One moment — I'm busy right now.",
]

# Played before each replan SLM iteration (2nd, 3rd agent call in a multi-step
# turn) so the gap isn't silent and the user knows the agent is mid-process —
# not just re-acknowledging. Pre-rendered at warmup.
REPLAN_STALL_PHRASES = [
    "Working through it.",
    "Still working through it.",
    "Let me piece that together.",
    "One more moment.",
    "Bear with me.",
    "Putting that together.",
]

# Played by `ThinkingWatchdog` at given intervals while a thinking-mode
# chat call is in flight, so the user knows the assistant hasn't stalled
# out. Pre-rendered at warmup.
THINKING_STALL_PHRASES = [
    "Still thinking on this.",
    "Working it through, give me a moment.",
    "Still considering it.",
    "Just a little more thought needed.",
]

# Spoken when no language model is available — either the no-LLM tier
# (llm.backend: none) or a remote OpenAI-compatible endpoint that's
# unreachable (Step 6). Played when the regex fast-path doesn't catch the
# request, so the user knows only basic commands work right now. Pre-rendered
# to `no_ai_cache` in `_warm_and_announce` and played via
# `_play_random_ack(cache=...)`.
NO_AI_PHRASES = [
    "I can't do that one without an AI model running.",
]

# Spoken when the configured remote LLM endpoint times out or errors mid-turn.
# Different from NO_AI_PHRASES (those are for llm.backend: none); these fire
# only when the backend is openai but RemoteUnreachable was raised. Pre-rendered
# to `llm_error_cache` in `_warm_and_announce`; played via `_speak_llm_error_fallback`.
LLM_ERROR_PHRASES = [
    "I can't reach the AI server right now. Basic commands still work.",
]

# Spoken when the agent invokes a tool that isn't loaded (a hallucinated tool
# name). The hallucinated-tool guard (core/agent_loop.py) blocks the turn here
# instead of letting the model fabricate an answer from priors. Pre-rendered to
# `tool_unavailable_cache` in `_warm_and_announce`, played via
# `_speak_tool_unavailable_fallback`. Keep these honest — no guessed data.
TOOL_UNAVAILABLE_PHRASES = [
    "I don't have a tool for that setup yet.",
]

# Cache attributes that require distinct wording. The final flag means the
# phrase is only needed when an LLM backend is configured.
STARTUP_CACHE_SPECS = (
    ("no_ai_cache", NO_AI_PHRASES, False),
    ("llm_error_cache", LLM_ERROR_PHRASES, True),
    ("tool_unavailable_cache", TOOL_UNAVAILABLE_PHRASES, True),
    ("barge_ack_cache", BARGE_ACK_PHRASES, False),
)

# Prefix phrases for calendar reminders spoken by the poll thread.
# The event summary is appended after a pause dash.
REMINDER_PREFIX_PHRASES = [
    "Just a reminder —",
    "Heads up —",
    "Quick reminder —",
    "Don't forget —",
]

# Topics for the startup greeting's "surprising fact" — rotated so the SLM
# isn't asked the same open-ended question every launch.
# Specificity is increased to prevent modal collapse to common trivia.
GREETING_TOPICS = [
    # Science & Nature
    "bizarre mechanisms of animal camouflage",
    "the hidden complexities of fungal networks",
    "extreme weather phenomena on other planets",
    "deep-sea extremophiles and how they survive",
    "the aerodynamics of insect flight",
    "unusual or extinct edible plants",
    # History & Culture
    "forgotten ancient technologies",
    "the origins of common everyday idioms",
    "unusual historical currencies",
    "misunderstood events in medieval history",
    "the logistics of ancient trade routes",
    # Math, Tech & Engineering
    "counterintuitive mathematical paradoxes",
    "accidental scientific discoveries",
    "early internet and computing history",
    "the engineering of ancient aqueducts and plumbing",
    "bizarre and obsolete units of measurement",
    # Arts & Human Experience
    "obscure musical instruments from around the world",
    "the chemistry behind historical art supplies",
    "fascinating psychological illusions",
    "the evolution of common household objects",
]
